"""
HYQUB — Dev Tools API
=======================

⚠️  DEVELOPMENT-ONLY ENDPOINTS. NEVER ENABLE IN PRODUCTION. ⚠️

These endpoints let the backend generate an ML-DSA keypair and sign
messages on the frontend's behalf, purely because the frontend has no
browser-side ML-DSA (WASM) implementation yet. This is a deliberate,
temporary shortcut for local development and demos ONLY.

In HYQUB's real security model, a user's ML-DSA private key must never
be generated by, transmitted to, or held by the backend — the entire
point of the quorum-approval design is that verifiers check a signature
produced by a key the user alone controls. An endpoint that generates
or signs with that key on the backend's behalf completely defeats that
guarantee.

These routes are only registered at all when
settings.environment == "development" (see main.py) — in any other
environment they simply don't exist (a request to them 404s, same as
any undefined route), rather than being logically gated behind a check
that could be misconfigured or bypassed.
"""

from fastapi import APIRouter, HTTPException, status

from app.crypto import mldsa
from app.crypto.encoding import decode_key_or_signature, encode_key_or_signature
from app.models.dev_tools import GenerateKeypairResponse, SignRequest, SignResponse

router = APIRouter(prefix="/dev", tags=["dev-only"])


@router.get(
    "/generate-keypair",
    response_model=GenerateKeypairResponse,
    status_code=status.HTTP_200_OK,
    summary="[DEV ONLY] Generate a fresh ML-DSA-65 keypair",
)
def generate_keypair() -> GenerateKeypairResponse:
    """
    Generate a new ML-DSA-65 keypair for local development/demo use.

    DEV ONLY — see module docstring.
    """
    public_key_bytes, secret_key_bytes = mldsa.generate_keypair()

    return GenerateKeypairResponse(
        public_key=encode_key_or_signature(public_key_bytes),
        secret_key=encode_key_or_signature(secret_key_bytes),
    )


@router.post(
    "/sign",
    response_model=SignResponse,
    status_code=status.HTTP_200_OK,
    summary="[DEV ONLY] Sign a message with a supplied ML-DSA secret key",
)
def sign(request: SignRequest) -> SignResponse:
    """
    Sign an arbitrary message using a caller-supplied ML-DSA secret key.

    DEV ONLY — see module docstring. Returns 400 if the secret key is
    malformed or the wrong length.
    """
    try:
        secret_key_bytes = decode_key_or_signature(request.secret_key, "secret_key")
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc

    try:
        signature_bytes = mldsa.sign(
            request.message.encode("utf-8"),
            secret_key_bytes,
        )
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc

    return SignResponse(signature=encode_key_or_signature(signature_bytes))
